### ISSUE TITLE
Problems with computing actinic flux

### ISSUE THREAD

**Issue by JZxxhh** [ghislainp/tartes#1]
It appears there is an issue with the new actinic flux computing function.  When runing the 'actinic_profile.py' script and setting dir_frac to be a value not being 0 or 1 (e.g., 0.5), there would raise an _ValueError: setting an array element with a sequence_. However, setting dir_frac equals to 0 or 1 would not trigger this error. Seems caused by the different shape of the RHS vector created by the _two_stream_vector_ function.

**Comment by ghislainp** [comment]
Thank you for reporting this bug. It is solved with commit https://github.com/ghislainp/tartes/commit/2274c39772d682e8df64c25b98bf2c41ad48082c

**Comment by JZxxhh** [comment]
Dear Picard:

Thanks a lot for your responce. I have another issue with the actinic flux computation and hope you could help me to solve. I'm testing the following code:

# semi-infinite medium
ssa = [40]       # in m^2/kg
density = [300]  # in kg/m^3
thickness = [1]  # in m
# depth at which the calculation is performed
z = arange(0, 100, 1) * 1e-2  # from 0 to 1m depth every cm
wl = [350e-9]
actinic_flux_profile = tartes.actinic_profile(
    wl, z, ssa, density, thickness, dir_frac=1,sza=60)
down_irr_profile, up_irr_profile = tartes.irradiance_profiles(
    wl, z, ssa, density, thickness, dir_frac=1,sza=60)

At suface (z=0), the test results told me that actinic_flux_profile[0] = 2.985, down_irr_profile[0] = 1.0 and up_irr_profile[0] = 0.992. 
Becasue dir_frac is set to 1, the direct incident intensity shoule be down_irr_profile[0]/cos(60) = 2 (no downward diffuse light), then the total actinic flux shoule be 2*(up_irr_profile + 0) + direct incident intensity = 3.984 instead of 2.985. Can you help me find where is the probelm in my calculation?

Indeed, in tartes.py line 1391 to 1392, you write "+ direct_only * (Gm[nl - 1] + 1) * np.exp(-taustar_z / mu))  # + 1 was mu before", I dont understand why you change the mu to 1 here. It seems that you force mu*F0 = 1 here, so I gauss F0 shoule be 1/mu whicj shoudl be reflected in actinic flux calculation? That would impact line 1437 in tartes function which you write: + (2 * Gm[nl - 1] + 2 * Gp[nl - 1] + 1 + diffuse2actinic) * np.exp(-taustar_z / mu), seems here + 1 shoule be +1/mu. 

By the way, I'm also a bit confused by the defination of totflux, does it mean the total downward irradiance (diffuse + direct) at surface? Then dir_frac shall be direct downward irradiance/ total downward irradiance, is that right? I'm asking it becasue I'm using the TUV model to provide the upper boundary condition for the TARTES model. It would be very helpful for me to clarify it.

Thanks again for your nice work on the TARETS model, hope I could get your resopnce soon.

Best regards,
Zhuang

-----原始邮件-----
发件人: "Ghislain Picard" ***@***.***>
发送时间: 2024-10-14 03:13:39 (星期一)
收件人: ghislainp/tartes ***@***.***>
抄送: "Zhuang Jiang" ***@***.***>, Author ***@***.***>
主题: Re: [ghislainp/tartes] Problems with computing actinic flux (Issue #1)


Thank you for reporting this bug. It is solved with commit 2274c39

**Comment by liboisq** [comment]
Dear Zhuang,

Thanks for your interest in TARTES.
For your information totflux in TARTES is a flux across the horizontal.
So it can be written F0 * mu0 + Fdiff, where F0 is the solar beam intensity.
dir_frac thus equals F0 * mu0 /(F0 * mu0 + Fdiff)

In practice we recommend to treat diffuse flux as a direct flux at mudiff = 48.2°.
So the fluxes can be written as a weighted sum of two fluxes (corresponding to two different incident angles).

In all the equations in tartes.py totflux F0 * mu0 (ie totflux) is factorized (does not appear in G terms, neither in vector V), so that all returned fluxes are scaled by totflux.
It means that you should multiply the output fluxes of tartes by F0 * mu0 to get actual fluxes.

In your case all incident radiation is direct, with sza=60° (mudir = 0.5), and as totflux = 1 it implies that F0 = 2.
The actinic flux equals 2  x (F- + F+) + F0 exp(-tau*/mu0), where F- and F+ are the diffuse fluxes.
At the surface F- = 0, and F+ = 0.992, so that Fact = 2*0.992+2 = 3.984.

So we confirm that there was an error in the definition of the actinic flux, with the term "1" now replaced by "1/mu".

Thanks a lot for noting this error!

Kind regards

**Comment by ghislainp** [comment]
Solved in 9fb807b62fb0a734b3996efd91bdef520ce00bf2

**Comment by JZxxhh** [comment]
Dear Libois,




Thanks for your clarification and small correction. Now the model parameters are pretty clear to me and I can continue my work with using the TARTES model properly. Thanks for your assistance. Cheers!




Best,

Zhuang

-----原始邮件-----
发件人:liboisq ***@***.***>
发送时间:2024-10-18 18:23:18 (星期五)
收件人: ghislainp/tartes ***@***.***>
抄送: "Zhuang Jiang" ***@***.***>, Author ***@***.***>
主题: Re: [ghislainp/tartes] Problems with computing actinic flux (Issue #1)






Dear Zhuang,

Thanks for your interest in TARTES.
For your information totflux in TARTES is a flux across the horizontal.
So it can be written F0 * mu0 + Fdiff, where F0 is the solar beam intensity.
dir_frac thus equals F0 * mu0 /(F0 * mu0 + Fdiff)

In practice we recommend to treat diffuse flux as a direct flux at mudiff = 48.2°.
So the fluxes can be written as a weighted sum of two fluxes (corresponding to two different incident angles).

In all the equations in tartes.py totflux F0 * mu0 (ie totflux) is factorized (does not appear in G terms, neither in vector V), so that all returned fluxes are scaled by totflux.
It means that you should multiply the output fluxes of tartes by F0 * mu0 to get actual fluxes.

In your case all incident radiation is direct, with sza=60° (mudir = 0.5), and as totflux = 1 it implies that F0 = 2.
The actinic flux equals 2 x (F- + F+) + F0 exp(-tau*/mu0), where F- and F+ are the diffuse fluxes.
At the surface F- = 0, and F+ = 0.992, so that Fact = 2*0.992+2 = 3.984.

So we confirm that there was an error in the definition of the actinic flux, with the term "1" now replaced by "1/mu".

Thanks a lot for noting this error!

Kind regards
